steps:
  - name: 'gcr.io/buildpacks/builder:v1'
    args:
      - 'build'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--pack-image=gcr.io/$PROJECT_ID/infinity-earn-bot'
      - '--path=.'
      - '--env=PORT=8080'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'infinity-earn-bot'
      - '--image=gcr.io/$PROJECT_ID/infinity-earn-bot'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--service-account=180728958840-compute@developer.gserviceaccount.com'
      - '--set-env-vars=BOT_TOKEN=7749505174:AAHI-_mABEpz0y-Cx_GKpYPj-8IFW2A5n5w,NOWPAY_API_KEY=MW7B3BH-82Z4YSK-M270EA7-VVX0JZ1,NOWPAY_IPN_SECRET=U1niR1kvuIbS1WCi7s3up34hKxH2McrL,CHANNEL_USERNAME=@InfinityEarn2x,ADMIN_CHANNEL_ID=-1003095776330,GCS_BUCKET_NAME=infinity-earn-bot-storage-470810,BASE_URL=https://infinity-earn-bot-abc123-uc.a.run.app'
substitutions:
  _PROJECT_ID: telegram-bot-project-470810
